// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAby7-R8wsRotuAdw0ZxslY7dCZzQ4XZIQ',
    appId: '1:601513932979:web:5415d68b5a199a139c18c6',
    messagingSenderId: '601513932979',
    projectId: 'cooker-bas',
    authDomain: 'cooker-bas.firebaseapp.com',
    storageBucket: 'cooker-bas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyfcCLKbNMnGBwYipZMznjWogPx4c0Mo0',
    appId: '1:601513932979:android:6870e29ebfd4ee2f9c18c6',
    messagingSenderId: '601513932979',
    projectId: 'cooker-bas',
    storageBucket: 'cooker-bas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxGGviXat1NnukVrGs9dmAlhqJe4x8EUY',
    appId: '1:601513932979:ios:c61398468b6332e39c18c6',
    messagingSenderId: '601513932979',
    projectId: 'cooker-bas',
    storageBucket: 'cooker-bas.appspot.com',
    iosBundleId: 'com.example.cooker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxGGviXat1NnukVrGs9dmAlhqJe4x8EUY',
    appId: '1:601513932979:ios:c61398468b6332e39c18c6',
    messagingSenderId: '601513932979',
    projectId: 'cooker-bas',
    storageBucket: 'cooker-bas.appspot.com',
    iosBundleId: 'com.example.cooker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAby7-R8wsRotuAdw0ZxslY7dCZzQ4XZIQ',
    appId: '1:601513932979:web:a74435dbd7e01ca29c18c6',
    messagingSenderId: '601513932979',
    projectId: 'cooker-bas',
    authDomain: 'cooker-bas.firebaseapp.com',
    storageBucket: 'cooker-bas.appspot.com',
  );
}
